### ISSUE TITLE
A doubt about VSOD task being unsupervised

### ISSUE THREAD

**Issue by gl490402850** [suyukun666/UFO#7]
Hi author, I would like to do further research based on your work, but I have some doubts that I hope you can answer for me. You mentioned in your paper that your model is unsupervised for the VSOD task, but I see that the code uses groundtruth for supervision, what is the reason for this?

**Comment by Gi-gigi** [comment]
Hi friend! I've noticed the same issue as you! The paper indeed states that the VSOD task is unsupervised, but the code still involves ground truth labels. They've only frozen the co-classification branch, which might barely qualify as semi-supervised, right? What's your take on this issue? Looking forward to your response.
